version: "3.7"

services:
  blog:
    image: PROJECT_VENDOR/PROJECT_NAME:DOCKER_IMAGE_TAG
    restart: always
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/fpm-ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m
    environment: 
      - APP_NAME
      - APP_ENV
      - APP_KEY
      - APP_DEBUG
      - APP_URL
      - APP_TIMEZONE
      - LOG_CHANNEL
      - LOG_SLACK_WEBHOOK_URL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - CACHE_DRIVER
      - QUEUE_CONNECTION